#! /bin/sh
export PATH="$HOME/env:$PATH"

brew bundle --file=- <<EOF
  # Tools
  brew "mas"
  brew "zsh"
  brew "the_silver_searcher"
  brew "tmux"
  brew "ranger"
  brew "wget"
  brew "jq"
  brew "yq"
  brew "watchman"
  brew "fswatch"
  brew "neovim"
  brew "python3"
  brew awscli
  brew ngrok
  brew sshuttle
  brew thefuck
  brew awscli
  brew bitwarden
  # Development
  brew "git"
  # dotfiles
  tap "thoughtbot/formulae"
  brew "rcm"
  # cask 
  brew "docker" --cask
  brew "android-studio" --cask
  brew "cryptomator" --cask
  brew "aws-vpn-client " --cask
  brew "robo-3t" --cask
  brew "fliqlo" --cask
  brew "mongodb-compass" --cask
  brew "dbeaver-community" --cask
EOF

# tmuxp
pip3 install tmuxp

#TODO: Pull dotfiles

defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
defaults write -g KeyRepeat -int 1 # normal minimum is 2 (30 ms)