#!/bin/bash

# Ensure Homebrew is installed
if ! command -v brew &>/dev/null; then
  echo "Homebrew not found. Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo "Homebrew is already installed. Updating Homebrew..."
  brew update
fi

# Ensure Brew Bundle is available
if ! brew command bundle &>/dev/null; then
  echo "Installing Brew Bundle..."
  brew tap homebrew/bundle
fi

echo "Starting application installation via Brew Bundle..."

# Brewfile for all applications
brew bundle --file=- <<EOF
# mac installer
brew install mas

# Browsers
brew "google-chrome"
brew "firefox"
brew "brave-browser"

# Communication
brew "slack"
brew "zoom"
brew "whatsapp"
brew "telegram"

# tools
brew "flux"
brew "raycast"
brew "notion"
brew "transmission"
brew "fliqlo"
brew "cryptomator"
brew "the-unarchiver"
brew "spacelauncher"
brew "android-file-transfer"
brew "homerow"
brew "rectangle"

# Media
brew "vlc"
brew "spotify"


# app store
# Amphetamine
mas install 937984704
# disk cleaner 
mas install 446243721
# urban vpn
mas install 1517772049
#  bitwarden
mas install 1352778147
# Cleanup outdated versions
echo "Cleaning up..."
EOF

brew cleanup

echo "Setup complete!"
