#! /bin/sh
export PATH="$HOME/env:$PATH"
brew bundle --file=- <<EOF
  # Browsers
  cask "google-chrome"
  cask "firefox"

  # Communication
  cask "slack"
  cask "skype"
  cask "zoomus"
  cask "telegram"

  # Tools
  cask "epichrome"
  cask "alfred"
  cask "iterm2"
  cask "rectangle"
  cask "cheatsheet"
  cask "flux"
  cask "drawio"
  cask "the-unarchiver"
  cask "notion"
  cask "spacelauncher"

  # Media
  cask "vlc"
  cask "spotify"


EOF

# Setup iTerm2
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/dotfiles-local/iterm2"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

